app = "magical-creature"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  NODE_ENV = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  cron = "supercronic /app/crontab"
