app = "your-app-name"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  # Set any environment variables your app needs
  NODE_ENV = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 3000
