app = "magical-creature"

kill_signal = "SIGINT"
kill_timeout = 5

[processes]
  app = "bin/server"
  cron = "supercronic /etc/crontab"

[env]
  NODE_ENV = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
# Only the main app process needs a service
process = "app"
internal_port = 3000
protocol = "tcp"

  [[services.ports]]
  port = 3000
